In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("Ames_Housing_Data.csv")

In [3]:
df.head()

,MSSubClass_160,MSSubClass_180,MSSubClass_190,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,...,RemodAge,TotalBath,TotalSF,TotalPorchSF,HasGarage,HasBasement,HasFireplace,HasPool,TotalOutdoorSF,SalePrice
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,5.0,3.5,2566.0,61.0,1.0,1.0,0.0,0.0,61.0,208500
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,31.0,2.5,2524.0,298.0,1.0,1.0,1.0,0.0,298.0,181500
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,6.0,3.5,2706.0,42.0,1.0,1.0,1.0,0.0,42.0,223500
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,36.0,2.0,2473.0,307.0,1.0,1.0,1.0,0.0,307.0,140000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,8.0,3.5,3343.0,276.0,1.0,1.0,1.0,0.0,276.0,250000

In [4]:
x = df.drop(['SalePrice'], axis=1)
y = df['SalePrice']

In [5]:
x

,MSSubClass_160,MSSubClass_180,MSSubClass_190,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,...,HouseAge,RemodAge,TotalBath,TotalSF,TotalPorchSF,HasGarage,HasBasement,HasFireplace,HasPool,TotalOutdoorSF
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,5.0,5.0,3.5,2566.0,61.0,1.0,1.0,0.0,0.0,61.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,31.0,31.0,2.5,2524.0,298.0,1.0,1.0,1.0,0.0,298.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,7.0,6.0,3.5,2706.0,42.0,1.0,1.0,1.0,0.0,42.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,91.0,36.0,2.0,2473.0,307.0,1.0,1.0,1.0,0.0,307.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,8.0,8.0,3.5,3343.0,276.0,1.0,1.0,1.0,0.0,276.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,8.0,7.0,2.5,2600.0,40.0,1.0,1.0,1.0,0.0,40.0
1456,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,32.0,22.0,3.0,3615.0,349.0,1.0,1.0,1.0,0.0,349.0
1457,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,69.0,4.0,2.0,3492.0,60.0,1.0,1.0,1.0,0.0,60.0
1458,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,60.0,14.0,2.0,2156.0,478.0,1.0,1.0,0.0,0.0,478.0
1459,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,43.0,43.0,2.5,2512.0,804.0,1.0,1.0,0.0,0.0,804.0

In [6]:
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [7]:
# train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [8]:
# standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [9]:


x_train = scaler.fit_transform(x_train)   # Fit + Transform
x_test = scaler.transform(x_test)         # Only Transform

Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_absolute_error, r2_score

In [11]:
regression = LinearRegression()
regression.fit(x_train, y_train)

LinearRegression()

In [12]:
y_pred = regression.predict(x_test)

In [13]:
r2 = r2_score(y_test, y_pred)

In [14]:
print(r2)

0.0016901610156057068

In [15]:
print(x.shape)
print(y.shape)

(1460, 282)
(1460,)

In [16]:
print(x_train.shape)
print(x_test.shape)

(1095, 282)
(365, 282)

In [17]:
print(regression.score(x_train, y_train))
print(regression.score(x_test, y_test))

0.9399131353673102
0.0016901610156057068

Ridge Regression

In [18]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

ridge = Ridge(alpha=10)

ridge.fit(x_train, y_train)

y_pred_ridge = ridge.predict(x_test)

print("MAE :", mean_absolute_error(y_test, y_pred_ridge))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred_ridge)))
print("R2 Score :", r2_score(y_test, y_pred_ridge))

MAE : 18645.914574087696
RMSE : 31809.433887292955
R2 Score : 0.8555609643100368

Lasso Regression

In [19]:
from sklearn.linear_model import Lasso
Lasso = Lasso(alpha = 0.001)

Lasso.fit(x_train, y_train)

y_pred_Lasso= Lasso.predict(x_test)

c:\Users\Kislay\OneDrive\Desktop\python\venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+11, tolerance: 6.648e+08
  model = cd_fast.enet_coordinate_descent(

In [20]:
print("MAE :", mean_absolute_error(y_test, y_pred_Lasso))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred_Lasso)))
print("R2 Score :", r2_score(y_test, y_pred_Lasso))

MAE : 18751.80398271301
RMSE : 34055.872100891786
R2 Score : 0.8344395063962238

Random Forest Regressor

In [32]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

Hyperparameter tuning using random search cv

In [22]:
y_pred_rf = rf.predict(x_test)

print("MAE :", mean_absolute_error(y_test, y_pred_rf))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("R2 Score :", r2_score(y_test, y_pred_rf))

MAE : 16858.49339726027
RMSE : 28485.033752219017
R2 Score : 0.8841739683713022

In [29]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2'],
    'bootstrap': [True, False]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=30,
    cv=5,
    scoring='r2',
    random_state=42,
    n_jobs=-1,
    verbose=2
)

random_search.fit(x_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [None, 10, 20, 30, 40],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='r2', verbose=2)

In [24]:
best_rf = random_search.best_estimator_

y_pred_hrf = best_rf.predict(x_test)

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred_hrf))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred_hrf)))
print("R2 Score :", r2_score(y_test, y_pred_hrf))

MAE : 16894.153506849314
RMSE : 29812.472245720204
R2 Score : 0.8731271533116671

In [26]:
import pickle
with open("rf.pkl", "wb") as file:
    pickle.dump(rf, file)

In [27]:
print(rf)

RandomForestRegressor(random_state=42)

In [33]:
print(rf.predict(x_test[:5]))

[139581.25 332857.56 115688.   157223.5  315167.81]

In [34]:
import pickle
with open("scaler.pkl", "wb") as f:
       pickle.dump(scaler, f)